version: "3.9"
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/master
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "master"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "54321:5432"

  angular:
    build: supportportalapp/.angular
    volumes:
      - 'supportportalapp./angular/usr/src/app'
    ports:
      - "4500:4500"


