jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    password: root
    username: root
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false